> /Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py(210)load_data()
    209     ipdb.set_trace()
--> 210     return training_dataset, testing_dataset
    211
Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '377', '378', '379', '380', '381', '382', '383', 'label', 'lat', 'lon'],
      dtype='object', length=387)
827         school
1390    non_school
1358    non_school
609         school
1628    non_school
           ...
825         school
838         school
1444    non_school
813         school
1619    non_school
Name: label, Length: 1284, dtype: object
571    school
586    school
399    school
439    school
734    school
        ...
149    school
748    school
511    school
773    school
31     school
Name: label, Length: 238, dtype: object
Traceback (most recent call last):
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 319, in <module>
    train_data, test_data = load_data(aoi, buffer, features, label)
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 210, in load_data
    return training_dataset, testing_dataset
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 210, in load_data
    return training_dataset, testing_dataset
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
If you suspect this is an IPython 8.7.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org
You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True