> /Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py(85)load_data()
     84
---> 85         train_df = merge_train.drop(columns=['UID', 'class_y', 'dataset', 'iso', 'rurban', 'Unnamed: 0'])
     86         test_df = merge_test.drop(columns=['UID', 'class_y', 'dataset', 'iso', 'rurban', 'Unnamed: 0'])
Traceback (most recent call last):
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 279, in <module>
    get_class_balance(train_data, test_data, results)
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 85, in load_data
    train_df = train_df.rename(columns={'class_x': 'label'})
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 85, in load_data
    train_df = train_df.rename(columns={'class_x': 'label'})
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
If you suspect this is an IPython 8.7.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org
You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True