> /Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py(93)load_data()
     92
---> 93         training_data = combined_train
     94         testing_data = combined_test
           lat        lon  connectivity  modis.LC_Type1.mode  ...      1020      1021      1022      1023
103 -25.229447  25.686488           1.0                   10  ...  0.566425 -0.394862  0.405432 -0.351195
391 -25.610500  24.535274           0.0                    7  ...  0.808870 -0.477167  0.339348  0.413525
252 -21.383479  27.413420           1.0                   10  ...  0.449563 -0.336054  0.022372 -0.037011
239 -22.718298  27.311323           0.0                   10  ...  0.471092 -0.630377  0.078786  0.286640
176 -20.858756  27.673338           0.0                   10  ...  0.306617 -0.454115  0.149132 -0.028077
..         ...        ...           ...                  ...  ...       ...       ...       ...       ...
32  -24.410541  25.511240           1.0                   13  ...  0.748759 -0.486795 -0.023367  0.024914
436 -24.618016  25.888407           1.0                   13  ...  0.676389 -0.262877  0.042488  0.019694
459 -24.906764  25.626596           0.0                   10  ...  0.630256 -0.238230  0.215959 -0.184607
15  -22.398665  26.705240           1.0                   13  ...  0.633556 -0.433906  0.135338  0.217521
28  -24.422119  25.467375           1.0                   10  ...  0.729060 -0.334718  0.026825 -0.242753
[634 rows x 1110 columns]
Traceback (most recent call last):
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 230, in <module>
    train_data, test_data = load_data(aoi, buffer, features)
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 93, in load_data
    training_data = combined_train
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 93, in load_data
    training_data = combined_train
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
If you suspect this is an IPython 8.7.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org
You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True