> /Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py(82)load_data()
     81
---> 82     training_dataset = shuffle(training_data)
     83     testing_dataset = shuffle(testing_data)
*** NameError: name 'training_dataset' is not defined
Index(['giga_id_school', 'lat', 'lon', 'connectivity', 'school_locations',
       'modis.LC_Type1.mode', 'modis.LC_Type1.var', 'modis.LC_Type1.evg_conif',
       'modis.LC_Type1.evg_broad', 'modis.LC_Type1.dcd_needle',
       ...
       '1015', '1016', '1017', '1018', '1019', '1020', '1021', '1022', '1023',
       'location'],
      dtype='object', length=1113)
Traceback (most recent call last):
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 166, in <module>
    train_data, test_data = load_data(aoi, buffer, features)
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 82, in load_data
    training_dataset = shuffle(training_data)
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 82, in load_data
    training_dataset = shuffle(training_data)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
If you suspect this is an IPython 8.7.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org
You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True