Creating instance of GB model...
Fitting data...
The hard predictions were right 53.21% of the time
Traceback (most recent call last):
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 287, in <module>
    gb.run_gb(
  File "/Users/kelseydoerksen/code/giga-connectivity/classifiers/gb.py", line 79, in run_gb
    cv_scoring = cross_validate_scoring(clf, X_test, y_test, ['accuracy', 'f1'], cv=5, results_dir=results_dir)
  File "/Users/kelseydoerksen/code/giga-connectivity/analysis/generating_results.py", line 10, in cross_validate_scoring
    cv_scoring = cross_validate(classifier, X_test, y_test, scoring=scoring, cv=cv)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 266, in cross_validate
    results = parallel(
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/joblib/parallel.py", line 864, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/joblib/parallel.py", line 782, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/joblib/parallel.py", line 263, in __call__
    return [func(*args, **kwargs)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/joblib/parallel.py", line 263, in <listcomp>
    return [func(*args, **kwargs)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/sklearn/utils/fixes.py", line 117, in __call__
    return self.function(*args, **kwargs)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 538, in fit
    n_stages = self._fit_stages(
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 615, in _fit_stages
    raw_predictions = self._fit_stage(
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 257, in _fit_stage
    tree.fit(X, residual, sample_weight=sample_weight, check_input=False)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/sklearn/tree/_classes.py", line 1247, in fit
    super().fit(
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/sklearn/tree/_classes.py", line 379, in fit
    builder.build(self.tree_, X, y, sample_weight)
KeyboardInterrupt